### ISSUE TITLE
kube-oidc-proxy has x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ningweiii** [tolson-vkn/dex-k8s-ldap#1]
Hi,
I find your repo very useful for the project I am working on.
Thank you for the details in the documentation.
I am having an issue to deploy kube-oidc-proxy which is not completed in the [section](https://github.com/tolson-vkn/dex-k8s-ldap#managed-way-kube-oidc-proxy). 
It would be great that I can get some guidelines from you.

I have a secret as bellow:
```yaml
apiVersion: v1
data:
  tls.crt: {{ BASE64 ssl/cert.pem}}
  tls.key: {{BASE64 ssl/key.pem}}
kind: Secret
metadata:
  name: kube-oidc-proxy-tls
  namespace: kube-oidc-proxy
type: kubernetes.io/tls
---
apiVersion: v1
data:
  oidc.ca-pem: {{ BASE64 ssl/ca.pem}}
  oidc.issuer-url: {{ BASE64 https://login.microsoftonline.com/{tenant}/oauth2/v2.0 }}
  oidc.username-claim: {{ BASE64 sub}}
  oidc.client-id: {{  BASE64 kubernetes}}
kind: Secret
metadata:
  name: kube-oidc-proxy-config
  namespace: kube-oidc-proxy
type: Opaque
```
Here I am not sure I am using the right values here.
tls.crt uses `ssl/cert.pem`
tls.key uses `ssl/key.pem`
oidc.ca-pem uses `ssl/ca.pem`

Finally I got x509: certificate signed by unknown error.
Do you by any chance know what I did wrong here?
Any help is much appreciated 

```bash
I0623 16:15:56.216473       1 probe.go:63] OIDC provider not yet initialized: oidc: authenticator not initialized
E0623 16:15:59.439829       1 oidc.go:224] oidc authenticator: initializing plugin: Get "https://login.microsoftonline.com/{mytenant}/oauth2/authorize/.well-known/openid-configuration": x509: certificate signed by unknown authority
```
